apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-permission-manager-cli
data:
  CLUSTER_NAME: "{{ .Values.kubernetes.cluster_name }}"
  CONTROL_PLANE_ADDRESS: "{{ .Values.kubernetes.control_plane_address }}"
  {{- if .Values.telegram.bot_api }}
  TELEGRAM_BOT_API: "{{ .Values.telegram.bot_api }}"
  {{- end }}
  {{- if .Values.telegram.chat_id }}
  TELEGRAM_CHAT_ID: "{{ .Values.telegram.chat_id }}"
  {{- end }}