apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: permission-manager-cli
subjects:
- kind: ServiceAccount
  name: permission-manager-cli
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: permission-manager-cli
  apiGroup: rbac.authorization.k8s.io